version: '2'
services:
  phorge:
    restart: always
    ports:
     - "62443:443"
     - "62080:80"
     - "62022:22"
    volumes:
     - /srv/docker/phorge/repos:/repos
    depends_on:
     - mysql
    links:
     - mysql
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_USER=root
     - MYSQL_PASS=phorge
     - PHORGE_REPOSITORY_PATH=/repos
     - PHORGE_HOST=phorge.localhost
    image: phorge
  mysql:
    restart: always
    volumes:
     - /srv/docker/phorge/mysql:/var/lib/mariadb
    image: mariadb:latest
    environment:
     - MYSQL_ROOT_PASSWORD=phorge